<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\Common.props" />

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <OutputType>WinExe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <ApplicationIcon>Resources\Next.ico</ApplicationIcon>
    <Version>5.2.0-preview.2</Version>
    <Authors>Launchbar</Authors>
    <Description>RunIT to the next level.</Description>
    <Copyright>Copyright © Mertsch $([System.DateTime]::UtcNow.Year)</Copyright>

    <IsPublishable>true</IsPublishable>
    <!-- https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#generateassemblyinfo -->
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="fm.Extensions.Wpf" Version="5.0.1" />
    <PackageReference Include="JetBrains.Annotations" Version="2024.2.0" />
    <PackageReference Include="Markdig.Wpf" Version="0.5.0.1" />
    <PackageReference Include="WpfScreenHelper" Version="2.1.1" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Resources\**\*.png;Resources\**\*.ico" />

    <Resource Include="Resources\**\*.png;Resources\**\*.ico" />
    <Resource Include="..\..\CHANGELOG.md" Link="CHANGELOG.md" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>