name: Build Launchbar

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x
    - name: Restore dependencies
      run: dotnet restore Source/Launchbar.sln
    - name: Build
      run: dotnet build Source/Launchbar.sln --no-restore --configuration Release
    - name: Test
      run: dotnet test Source/Launchbar.sln --no-build --verbosity normal
    - name: Publish
      run: dotnet publish Source/Launchbar.sln --no-build --configuration Release
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Launchbar
        path: Source/artifacts/publish/Launchbar/release/**
        if-no-files-found: error
