name: Build Launchbar

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore Source/Launchbar.sln
    - name: Build
      run: dotnet build Source/Launchbar.sln --no-restore
    - name: Test
      run: dotnet test Source/Launchbar.sln --no-build --verbosity normal
